variables:
  nproc: "1"


before_script:
  - nproc=`grep -c '^processor' /proc/cpuinfo`
  - echo "nproc = $nproc"
   
#========== Pipeline ==================
stages:
  - configure
  - compile
#=====================================

#============== configure ============
configure-linux:
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_ID}"
    expire_in: 1 hour
    paths:
      - build
      - lib
      - lib/Debug
      - bin
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug  ..
    - echo "configure | ${CI_PROJECT_DIR}"
  stage: configure
  tags:
    - linux
#============== compile ============
make-linux:
  dependencies:
    - configure-linux
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_ID}"
    expire_in: 1 hour # optional expiry
    paths:
      - build
      - bin
      - lib
      - lib/Debug
      
  stage: compile
  script:
    - cd build
    - make -j$nproc
    - echo "compile | ${CI_PROJECT_DIR}"
  tags:
    - linux

after_script:
  - echo "End CI" # todo: run report script
