language: cpp
dist: bionic

git:
  depth: 1
  quiet: true

matrix:
  include:
    - name: linux (clang8)
      os: linux
      env: TOOLCHAIN=clang
      script:
       - mkdir build && cd build
       - cmake  ..
       - make -j $(nproc)
       - cd ../Utest/Methods
       - ../../bin/jpsreport ini_Methods.xml
       - python runtest_Methods_C.py

    - name: linux (gcc9)
      os: linux
      env: TOOLCHAIN=gcc
      script:
       - mkdir build && cd build
       - cmake ..
       - make -j $(nproc)
       - cd ../Utest/Methods
       - ../../bin/jpsreport ini_Methods.xml

before_install:
    - source .travis_before_install.bash
    - python --version
    - pip install numpy
    - pip install scipy
    - pip install logging

install:
    - source .travis_install.bash
