language: cpp
dist: bionic

git:
  depth: 1
  quiet: true

matrix:
  include:
    - name: linux (clang8)
      os: linux
      env: TOOLCHAIN=clang
      script:
       - mkdir build && cd build
       - cmake  ..
       - make -j $(nproc)
       - cd ../Utest/Methods
       - ../../bin/jpsreport ini_Methods.xml
       - python runtest_Method_C.py

    - name: linux (gcc9)
      os: linux
      env: TOOLCHAIN=gcc
      script:
       - mkdir build && cd build
       - cmake ..
       - make -j $(nproc)
       - cd ../Utest/Methods
       - ../../bin/jpsreport ini_Methods.xml

before_install:
    - source .travis_before_install.bash
    - choco install python -- version 3.7.4
    - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:%PATH

install:
    - source .travis_install.bash
    - pip install --user --upgrade pip
    - pip install --user numpy
    - pip install --user scipy
    - pip install --user logging
