language: cpp
dist: bionic

git:
  depth: 1
  quiet: true

matrix:
  include:
    - name: linux (clang8)
      os: linux
      env: TOOLCHAIN=clang
      script:
       - mkdir build && cd build
       - cmake  ..
       - make -j $(nproc)
       - cd ../Utest/Methods
       - ../../bin/jpsreport ini_Methods.xml
       - python runtest_Methods_C.py

    - name: linux (gcc9)
      os: linux
      env: TOOLCHAIN=gcc
      script:
       - mkdir build && cd build
       - cmake ..
       - make -j $(nproc)
       - cd ../Utest/Methods
       - ../../bin/jpsreport ini_Methods.xml

before_install:
    - source .travis_before_install.bash
    - sudo apt-get update
    - sudo apt-get install python3
    - python3 --version
    - pip install --user --upgrade pip
    - pip install --user numpy
    - pip install --user scipy
    - pip install --user logging

install:
    - source .travis_install.bash
